import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          {/* header */}
          <Header />

          <main className="min-h-screen pt-10 px-6">{children}</main>
          {/* footer */}
          <footer className="bg-blue-50 py-10">
            <div
              className="container mx-auto px-4 text-center
          text-gray-600"
            >
              <p className="font-semibold text-gray-700">
                FinAI – Smart Expense Tracking & Budget Management
              </p>
              <p className="font-mediumm mt-5">
                Designed & Developed by Bhoomi Gupta
              </p>
            </div>
          </footer>

          <Toaster position="top-center" richColors closeButton />
        </body>
      </html>
    </ClerkProvider>
  );
}
